name: Build single job
  uses: Mondtic/build-jenkins-job@main
    with:
      jenkins-url: "http://192.168.100.158:9090/job/notificacion-slack/"
      jenkins-token: "1196cfaf3385f01f1cbf19d20c577b10d8"
      jenkins-user: "birc"
      jenkins-job: "notificacion-slack"
      jenkins-job-params: "{'stringparam': 'stringvalue', 'booleanparam': false}"
      jenkins-wait-job: "no-wait"
      jenkins-ssl-verify: "true"